name: Version Increment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          git config --global user.name 'Automat CI'
          git config --global user.email 'info@runautomat.com'
      - run: npm version patch
      - run: git push
